// <auto-generated />
namespace Proyecto_FunCase_WEBLY.FunCaseMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FunCaseCompras : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FunCaseCompras));
        
        string IMigrationMetadata.Id
        {
            get { return "202108172304559_FunCaseCompras"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
