namespace Proyecto_FunCase_WEBLY.FunCaseMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FunCaseAdjustment5 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Direccions", "Cliente_ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Direccions", "Estado_EstadoID", "dbo.Estadoes");
            DropForeignKey("dbo.DetallesPedidoes", "Pedido_PedidoID", "dbo.Pedidoes");
            DropForeignKey("dbo.DetallesPedidoes", "Producto_ProductoID", "dbo.Productoes");
            DropForeignKey("dbo.Pedidoes", "Cliente_ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Productoes", "Material_MaterialID", "dbo.Materials");
            DropForeignKey("dbo.Productoes", "Modelo_ModeloID", "dbo.Modeloes");
            DropForeignKey("dbo.Modeloes", "Marca_MarcaID", "dbo.Marcas");
            DropForeignKey("dbo.Funda_Diseno", "Cliente_ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Funda_Diseno", "Producto_ProductoID", "dbo.Productoes");
            DropForeignKey("dbo.Imagen_Diseno", "FundaDiseno_Funda_DisenoID", "dbo.Funda_Diseno");
            DropForeignKey("dbo.Imagen_Diseno", "Imagen_ImagenID", "dbo.Imagens");
            DropForeignKey("dbo.Imagens", "Designer_DesignerID", "dbo.Designers");
            DropIndex("dbo.Direccions", new[] { "Cliente_ClienteID" });
            DropIndex("dbo.Direccions", new[] { "Estado_EstadoID" });
            DropIndex("dbo.DetallesPedidoes", new[] { "Pedido_PedidoID" });
            DropIndex("dbo.DetallesPedidoes", new[] { "Producto_ProductoID" });
            DropIndex("dbo.Pedidoes", new[] { "Cliente_ClienteID" });
            DropIndex("dbo.Productoes", new[] { "Material_MaterialID" });
            DropIndex("dbo.Productoes", new[] { "Modelo_ModeloID" });
            DropIndex("dbo.Modeloes", new[] { "Marca_MarcaID" });
            DropIndex("dbo.Funda_Diseno", new[] { "Cliente_ClienteID" });
            DropIndex("dbo.Funda_Diseno", new[] { "Producto_ProductoID" });
            DropIndex("dbo.Imagen_Diseno", new[] { "FundaDiseno_Funda_DisenoID" });
            DropIndex("dbo.Imagen_Diseno", new[] { "Imagen_ImagenID" });
            DropIndex("dbo.Imagens", new[] { "Designer_DesignerID" });
            RenameColumn(table: "dbo.Direccions", name: "Cliente_ClienteID", newName: "ClienteID");
            RenameColumn(table: "dbo.Direccions", name: "Estado_EstadoID", newName: "EstadoID");
            RenameColumn(table: "dbo.DetallesPedidoes", name: "Pedido_PedidoID", newName: "PedidoID");
            RenameColumn(table: "dbo.DetallesPedidoes", name: "Producto_ProductoID", newName: "ProductoID");
            RenameColumn(table: "dbo.Pedidoes", name: "Cliente_ClienteID", newName: "ClienteID");
            RenameColumn(table: "dbo.Productoes", name: "Material_MaterialID", newName: "MaterialID");
            RenameColumn(table: "dbo.Productoes", name: "Modelo_ModeloID", newName: "ModeloID");
            RenameColumn(table: "dbo.Modeloes", name: "Marca_MarcaID", newName: "MarcaID");
            RenameColumn(table: "dbo.Funda_Diseno", name: "Cliente_ClienteID", newName: "ClienteID");
            RenameColumn(table: "dbo.Funda_Diseno", name: "Producto_ProductoID", newName: "ProductoID");
            RenameColumn(table: "dbo.Imagen_Diseno", name: "FundaDiseno_Funda_DisenoID", newName: "Funda_DisenoID");
            RenameColumn(table: "dbo.Imagen_Diseno", name: "Imagen_ImagenID", newName: "ImagenID");
            RenameColumn(table: "dbo.Imagens", name: "Designer_DesignerID", newName: "DesignerID");
            AddColumn("dbo.Pedidoes", "MetodoPagoID", c => c.Int(nullable: false));
            AlterColumn("dbo.Direccions", "ClienteID", c => c.Int(nullable: false));
            AlterColumn("dbo.Direccions", "EstadoID", c => c.Int(nullable: false));
            AlterColumn("dbo.Estadoes", "Nombre", c => c.String(nullable: false));
            AlterColumn("dbo.AspNetUsers", "Telefono", c => c.String(nullable: false));
            AlterColumn("dbo.DetallesPedidoes", "PedidoID", c => c.Int(nullable: false));
            AlterColumn("dbo.DetallesPedidoes", "ProductoID", c => c.Int(nullable: false));
            AlterColumn("dbo.Pedidoes", "ClienteID", c => c.Int(nullable: false));
            AlterColumn("dbo.Productoes", "Nombre", c => c.String(nullable: false));
            AlterColumn("dbo.Productoes", "MaterialID", c => c.Int(nullable: false));
            AlterColumn("dbo.Productoes", "ModeloID", c => c.Int(nullable: false));
            AlterColumn("dbo.Modeloes", "MarcaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Funda_Diseno", "Imagen", c => c.String(nullable: false));
            AlterColumn("dbo.Funda_Diseno", "ClienteID", c => c.Int(nullable: false));
            AlterColumn("dbo.Funda_Diseno", "ProductoID", c => c.Int(nullable: false));
            AlterColumn("dbo.Imagen_Diseno", "Funda_DisenoID", c => c.Int(nullable: false));
            AlterColumn("dbo.Imagen_Diseno", "ImagenID", c => c.Int(nullable: false));
            AlterColumn("dbo.Imagens", "Ruta", c => c.String(nullable: false));
            AlterColumn("dbo.Imagens", "DesignerID", c => c.Int(nullable: false));
            CreateIndex("dbo.Direccions", "ClienteID");
            CreateIndex("dbo.Direccions", "EstadoID");
            CreateIndex("dbo.DetallesPedidoes", "ProductoID");
            CreateIndex("dbo.DetallesPedidoes", "PedidoID");
            CreateIndex("dbo.Pedidoes", "ClienteID");
            CreateIndex("dbo.Productoes", "MaterialID");
            CreateIndex("dbo.Productoes", "ModeloID");
            CreateIndex("dbo.Modeloes", "MarcaID");
            CreateIndex("dbo.Funda_Diseno", "ProductoID");
            CreateIndex("dbo.Funda_Diseno", "ClienteID");
            CreateIndex("dbo.Imagen_Diseno", "Funda_DisenoID");
            CreateIndex("dbo.Imagen_Diseno", "ImagenID");
            CreateIndex("dbo.Imagens", "DesignerID");
            AddForeignKey("dbo.Direccions", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Direccions", "EstadoID", "dbo.Estadoes", "EstadoID", cascadeDelete: true);
            AddForeignKey("dbo.DetallesPedidoes", "PedidoID", "dbo.Pedidoes", "PedidoID", cascadeDelete: true);
            AddForeignKey("dbo.DetallesPedidoes", "ProductoID", "dbo.Productoes", "ProductoID", cascadeDelete: true);
            AddForeignKey("dbo.Pedidoes", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Productoes", "MaterialID", "dbo.Materials", "MaterialID", cascadeDelete: true);
            AddForeignKey("dbo.Productoes", "ModeloID", "dbo.Modeloes", "ModeloID", cascadeDelete: true);
            AddForeignKey("dbo.Modeloes", "MarcaID", "dbo.Marcas", "MarcaID", cascadeDelete: true);
            AddForeignKey("dbo.Funda_Diseno", "ClienteID", "dbo.Clientes", "ClienteID", cascadeDelete: true);
            AddForeignKey("dbo.Funda_Diseno", "ProductoID", "dbo.Productoes", "ProductoID", cascadeDelete: true);
            AddForeignKey("dbo.Imagen_Diseno", "Funda_DisenoID", "dbo.Funda_Diseno", "Funda_DisenoID", cascadeDelete: true);
            AddForeignKey("dbo.Imagen_Diseno", "ImagenID", "dbo.Imagens", "ImagenID", cascadeDelete: true);
            AddForeignKey("dbo.Imagens", "DesignerID", "dbo.Designers", "DesignerID", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Imagens", "DesignerID", "dbo.Designers");
            DropForeignKey("dbo.Imagen_Diseno", "ImagenID", "dbo.Imagens");
            DropForeignKey("dbo.Imagen_Diseno", "Funda_DisenoID", "dbo.Funda_Diseno");
            DropForeignKey("dbo.Funda_Diseno", "ProductoID", "dbo.Productoes");
            DropForeignKey("dbo.Funda_Diseno", "ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.Modeloes", "MarcaID", "dbo.Marcas");
            DropForeignKey("dbo.Productoes", "ModeloID", "dbo.Modeloes");
            DropForeignKey("dbo.Productoes", "MaterialID", "dbo.Materials");
            DropForeignKey("dbo.Pedidoes", "ClienteID", "dbo.Clientes");
            DropForeignKey("dbo.DetallesPedidoes", "ProductoID", "dbo.Productoes");
            DropForeignKey("dbo.DetallesPedidoes", "PedidoID", "dbo.Pedidoes");
            DropForeignKey("dbo.Direccions", "EstadoID", "dbo.Estadoes");
            DropForeignKey("dbo.Direccions", "ClienteID", "dbo.Clientes");
            DropIndex("dbo.Imagens", new[] { "DesignerID" });
            DropIndex("dbo.Imagen_Diseno", new[] { "ImagenID" });
            DropIndex("dbo.Imagen_Diseno", new[] { "Funda_DisenoID" });
            DropIndex("dbo.Funda_Diseno", new[] { "ClienteID" });
            DropIndex("dbo.Funda_Diseno", new[] { "ProductoID" });
            DropIndex("dbo.Modeloes", new[] { "MarcaID" });
            DropIndex("dbo.Productoes", new[] { "ModeloID" });
            DropIndex("dbo.Productoes", new[] { "MaterialID" });
            DropIndex("dbo.Pedidoes", new[] { "ClienteID" });
            DropIndex("dbo.DetallesPedidoes", new[] { "PedidoID" });
            DropIndex("dbo.DetallesPedidoes", new[] { "ProductoID" });
            DropIndex("dbo.Direccions", new[] { "EstadoID" });
            DropIndex("dbo.Direccions", new[] { "ClienteID" });
            AlterColumn("dbo.Imagens", "DesignerID", c => c.Int());
            AlterColumn("dbo.Imagens", "Ruta", c => c.String());
            AlterColumn("dbo.Imagen_Diseno", "ImagenID", c => c.Int());
            AlterColumn("dbo.Imagen_Diseno", "Funda_DisenoID", c => c.Int());
            AlterColumn("dbo.Funda_Diseno", "ProductoID", c => c.Int());
            AlterColumn("dbo.Funda_Diseno", "ClienteID", c => c.Int());
            AlterColumn("dbo.Funda_Diseno", "Imagen", c => c.String());
            AlterColumn("dbo.Modeloes", "MarcaID", c => c.Int());
            AlterColumn("dbo.Productoes", "ModeloID", c => c.Int());
            AlterColumn("dbo.Productoes", "MaterialID", c => c.Int());
            AlterColumn("dbo.Productoes", "Nombre", c => c.String());
            AlterColumn("dbo.Pedidoes", "ClienteID", c => c.Int());
            AlterColumn("dbo.DetallesPedidoes", "ProductoID", c => c.Int());
            AlterColumn("dbo.DetallesPedidoes", "PedidoID", c => c.Int());
            AlterColumn("dbo.AspNetUsers", "Telefono", c => c.String());
            AlterColumn("dbo.Estadoes", "Nombre", c => c.String());
            AlterColumn("dbo.Direccions", "EstadoID", c => c.Int());
            AlterColumn("dbo.Direccions", "ClienteID", c => c.Int());
            DropColumn("dbo.Pedidoes", "MetodoPagoID");
            RenameColumn(table: "dbo.Imagens", name: "DesignerID", newName: "Designer_DesignerID");
            RenameColumn(table: "dbo.Imagen_Diseno", name: "ImagenID", newName: "Imagen_ImagenID");
            RenameColumn(table: "dbo.Imagen_Diseno", name: "Funda_DisenoID", newName: "FundaDiseno_Funda_DisenoID");
            RenameColumn(table: "dbo.Funda_Diseno", name: "ProductoID", newName: "Producto_ProductoID");
            RenameColumn(table: "dbo.Funda_Diseno", name: "ClienteID", newName: "Cliente_ClienteID");
            RenameColumn(table: "dbo.Modeloes", name: "MarcaID", newName: "Marca_MarcaID");
            RenameColumn(table: "dbo.Productoes", name: "ModeloID", newName: "Modelo_ModeloID");
            RenameColumn(table: "dbo.Productoes", name: "MaterialID", newName: "Material_MaterialID");
            RenameColumn(table: "dbo.Pedidoes", name: "ClienteID", newName: "Cliente_ClienteID");
            RenameColumn(table: "dbo.DetallesPedidoes", name: "ProductoID", newName: "Producto_ProductoID");
            RenameColumn(table: "dbo.DetallesPedidoes", name: "PedidoID", newName: "Pedido_PedidoID");
            RenameColumn(table: "dbo.Direccions", name: "EstadoID", newName: "Estado_EstadoID");
            RenameColumn(table: "dbo.Direccions", name: "ClienteID", newName: "Cliente_ClienteID");
            CreateIndex("dbo.Imagens", "Designer_DesignerID");
            CreateIndex("dbo.Imagen_Diseno", "Imagen_ImagenID");
            CreateIndex("dbo.Imagen_Diseno", "FundaDiseno_Funda_DisenoID");
            CreateIndex("dbo.Funda_Diseno", "Producto_ProductoID");
            CreateIndex("dbo.Funda_Diseno", "Cliente_ClienteID");
            CreateIndex("dbo.Modeloes", "Marca_MarcaID");
            CreateIndex("dbo.Productoes", "Modelo_ModeloID");
            CreateIndex("dbo.Productoes", "Material_MaterialID");
            CreateIndex("dbo.Pedidoes", "Cliente_ClienteID");
            CreateIndex("dbo.DetallesPedidoes", "Producto_ProductoID");
            CreateIndex("dbo.DetallesPedidoes", "Pedido_PedidoID");
            CreateIndex("dbo.Direccions", "Estado_EstadoID");
            CreateIndex("dbo.Direccions", "Cliente_ClienteID");
            AddForeignKey("dbo.Imagens", "Designer_DesignerID", "dbo.Designers", "DesignerID");
            AddForeignKey("dbo.Imagen_Diseno", "Imagen_ImagenID", "dbo.Imagens", "ImagenID");
            AddForeignKey("dbo.Imagen_Diseno", "FundaDiseno_Funda_DisenoID", "dbo.Funda_Diseno", "Funda_DisenoID");
            AddForeignKey("dbo.Funda_Diseno", "Producto_ProductoID", "dbo.Productoes", "ProductoID");
            AddForeignKey("dbo.Funda_Diseno", "Cliente_ClienteID", "dbo.Clientes", "ClienteID");
            AddForeignKey("dbo.Modeloes", "Marca_MarcaID", "dbo.Marcas", "MarcaID");
            AddForeignKey("dbo.Productoes", "Modelo_ModeloID", "dbo.Modeloes", "ModeloID");
            AddForeignKey("dbo.Productoes", "Material_MaterialID", "dbo.Materials", "MaterialID");
            AddForeignKey("dbo.Pedidoes", "Cliente_ClienteID", "dbo.Clientes", "ClienteID");
            AddForeignKey("dbo.DetallesPedidoes", "Producto_ProductoID", "dbo.Productoes", "ProductoID");
            AddForeignKey("dbo.DetallesPedidoes", "Pedido_PedidoID", "dbo.Pedidoes", "PedidoID");
            AddForeignKey("dbo.Direccions", "Estado_EstadoID", "dbo.Estadoes", "EstadoID");
            AddForeignKey("dbo.Direccions", "Cliente_ClienteID", "dbo.Clientes", "ClienteID");
        }
    }
}
