// <auto-generated />
namespace Proyecto_FunCase_WEBLY.FunCaseMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FunCaseInitial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FunCaseInitial1));
        
        string IMigrationMetadata.Id
        {
            get { return "202108022106103_FunCaseInitial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
